export const GET_ALL_USERS = "GET_ALL_USERS";

export const ADD_SENDER = "ADD_SENDER";
export const ADD_RECEIVER = "ADD_RECEIVER";

export const UPDATE_BALANCES = "UPDATE_BALANCES";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";

export const TRANSFER_COMPLETE = "TRANSFER_COMPLETE";

export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";